select * from dbo.coviddeaths
order by 3,4

select * from dbo.covidvaccination
order by 3,4

select Location, date, total_cases, new_cases, total_deaths, population 
From dbo.coviddeaths order by 1,2

--Looking at Total Cases Vs Total Deaths

select location, date, total_cases, total_deaths, (total_deaths/total_cases)*100 as Death_Percentage
from dbo.coviddeaths
order by Death_Percentage

--Getting look into the data in decreasing order of Death Percentage
--Query generated by Self

select location, date, total_cases, total_deaths, (total_deaths/total_cases)*100 as Death_Percentage
from dbo.coviddeaths
order by Death_Percentage desc

--Getting look into data of location=India in dcreasing order of Death-Percentage
--Query By Self

select location, date, total_cases, total_deaths, (total_deaths/total_cases)*100 as Death_Percentage
from dbo.coviddeaths where location='India'
order by Death_Percentage desc

--Getting look into data of location where states in dcreasing order of Death-Percentage
--Shows likelihood of dying if you contract covid in your country

select location, date, total_cases, total_deaths, (total_deaths/total_cases)*100 as Death_Percentage
from dbo.coviddeaths where location like '%states%'
order by Death_Percentage desc



--Looking at Total Cases Vs Population
--Shows what percentage of population got covid

select location, date, total_cases, population, (total_cases/population)*100 as Covid_Percentage
from dbo.coviddeaths where location like '%states%'
order by 1,2


--Looking at Countries with Highest Infection Rate compared to Population

select location, population, Max(total_cases) as HighestInfectionCount, Max((total_cases/population))*100 as PercentPopulationInfected
from dbo.coviddeaths
Group by location,population
order by PercentPopulationInfected desc

--Self Query

select location, population, Max(total_cases) as HighestInfectionCount, Max((total_cases/population))*100 as PercentPopulationInfected
from dbo.coviddeaths where location='India'
Group by location,population
order by PercentPopulationInfected desc

--Showing Countries with Highest Death Count per population

select location,max(cast(total_deaths as int)) as TotalDeathcount
from dbo.coviddeaths
group by Location
order by TotalDeathcount desc

--Only showing countries with Highest Death count and excluding Locations where continent =Null like World, Lower Income, Moddle Income

select location,max(cast(total_deaths as int)) as TotalDeathcount
from dbo.coviddeaths
where continent is not null
group by Location
order by TotalDeathcount desc


--Lets Break things down by Continent

select location,max(cast(total_deaths as int)) as TotalDeathcount
from dbo.coviddeaths
where continent is not null
group by location
order by TotalDeathcount desc

--But the above query shows incorrect figures like for North America it includes the data of only USA and not Canada and other country
--Similarly for Asia, it gives the data for only India
--The below query shows the correct figures

--Showing continents with the Highest death count per population

select location,max(cast(total_deaths as int)) as TotalDeathcount
from dbo.coviddeaths
where continent is null
group by location
order by TotalDeathcount desc

--or we can even do this (Self) (Wrong)

select continent, sum(cast(total_deaths as int)) as TotalDeathCount
from dbo.coviddeaths
where continent is not null
group by continent
order by TotalDeathCount desc

--Global Numbers
--Showing Total cases, death, death percentage each day by date across the world

select date, sum(new_cases)as WorldNewCases,sum(cast(new_deaths as int )) as WorldDeathCases, (sum(cast(new_deaths as int ))/sum(new_cases))*100 as DeathPercentage
from dbo.coviddeaths
where continent is not null
group by date
order by 1,2

--Shwoing total cases, total_deaths, and Death Percentage as a whole

select sum(new_cases)as WorldNewCases,sum(cast(new_deaths as int )) as WorldDeathCases, (sum(cast(new_deaths as int ))/sum(new_cases))*100 as DeathPercentage
from dbo.coviddeaths
where continent is not null
order by 1,2

--Joining The two tables

select * from dbo.coviddeaths dea join dbo.covidvaccination vac 
on dea.location = vac.location
and dea.date = vac.date

--Looking at Total Populations Vs Vaccinations

select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations 
from dbo.coviddeaths dea 
join dbo.covidvaccination vac 
on dea.location = vac.location
and dea.date = vac.date
where dea.continent is not null
order by 2,3

select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations,
sum(cast(vac.new_vaccinations as int)) over (partition by dea.location order by dea.location,dea.date)
from dbo.coviddeaths dea 
join dbo.covidvaccination vac 
on dea.location = vac.location
and dea.date = vac.date
where dea.continent is not null
order by 2,3


--Use CTE
--We wanted to calculate RollingPeopleVaccinated/Population but since RollingPeopleVaccinated is a alias made, we cant use directly
--thus we can have two ways- Use of CTE and Temp Table

with PopvsVac (Continent, location, date, population,new_vaccinations, RollingPeopleVaccinated)
as 
(
select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations,
sum(cast(vac.new_vaccinations as int)) over (partition by dea.location order by dea.location,dea.date)
as RollingPeopleVaccinated 
from dbo.coviddeaths dea 
join dbo.covidvaccination vac 
on dea.location = vac.location
and dea.date = vac.date
where dea.continent is not null
--order by 2,3
)
select * , (RollingPeopleVaccinated/Population)*100 
from PopvsVac


--Temp Table

Drop table if exists #PercentPopulationVaccinated
Create Table #PercentPopulationVaccinated
(
continent nvarchar(255),
location nvarchar(255),
date datetime,
population numeric,
new_vaccinations numeric,
RollingPeopleVaccinated numeric
)

Insert into #PercentPopulationVaccinated
select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations,
sum(cast(vac.new_vaccinations as int)) over (partition by dea.location order by dea.location,dea.date)
from dbo.coviddeaths dea 
join dbo.covidvaccination vac 
on dea.location = vac.location
and dea.date = vac.date
--where dea.continent is not null
--order by 2,3

select * , (RollingPeopleVaccinated/Population)*100 
from #PercentPopulationVaccinated



-- Creating View to store data for later visualizations

Create View PercentPopulationVaccinated2 as
Select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations
, SUM(CONVERT(int,vac.new_vaccinations)) OVER (Partition by dea.Location Order by dea.location, dea.Date) as RollingPeopleVaccinated
--, (RollingPeopleVaccinated/population)*100
From dbo.coviddeaths dea
Join dbo.covidvaccination vac
	On dea.location = vac.location
	and dea.date = vac.date
where dea.continent is not null 

select * from PercentPopulationVaccinated2